core/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('usuarios.urls', namespace='usuarios')),
    path('clientes/', include('clientes.urls', namespace='clientes')),
    path('finanzas/', include('finanzas.urls', namespace='finanzas')),
    path('proyectos/', include('proyectos.urls', namespace='proyectos')),
    path('reportes/', include('reportes.urls', namespace='reportes')),
    path('rrhh/', include('rrhh.urls', namespace='rrhh')),
    path('socios/', include('socios.urls', namespace='socios')),
    path('web/', include('web.urls', namespace='web')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

proyectos/urls.py
from django.urls import path
from . import views
from .views import *


app_name="proyectos"

urlpatterns = [
   
    path('proyectos/', views.app_proyectos, name = 'proyectos'),

    path('listar/', views.listar_proyectos, name='listar_proyectos'),
    path('crear/', views.crear_proyecto, name='crear_proyecto'),
    path('ver/<int:pk>/', views.ver_proyecto, name='ver_proyecto'),
    
    path('editar_empleado/<str:pk>/', views.editar_proyecto, name='editar_proyecto'),
    path('eliminar/<str:pk>/', views.eliminar_proyecto, name='eliminar_proyecto'),
    
    # Subproyectos
    path('subproyectos', views.proyectos_y_subproyectos, name='subproyectos'),    
    path('subproyectos/crear/', views.crear_subproyecto, name='crear_subproyecto'),
    path('subproyectos/<str:pk>/', views.actualizar_subproyecto, name='actualizar_subproyecto'),
    path('subproyectos/<str:pk>/eliminar', views.eliminar_subproyecto, name='eliminar_subproyecto'),
    

 

    
]

web/urls.py
from django.urls import path
from . import views
from .views import *    


app_name="web"

urlpatterns = [
   
    path('web/', views.appWeb, name = 'web'),
    path('listar/', views.listar, name = 'listarCompras'),
    path('separarLote/', views.separar_lote , name = 'separarLote'),
    path('pag_web/', views.pag_web, name = 'pag_web'),

    
]
    

proyectos/models.py
from django.db import models
from ubigeo.models import Distrito

class Proyectos(models.Model):
    class estado(models.TextChoices):

            ACTIVO = "ACTIVO"
            VENDIDO= "VENDIDO"
            PENDIENTE = "PENDIENTE"

    estado = models.CharField(choices=estado.choices, default="ACTIVO", max_length=30, )
    nombre = models.CharField(max_length=50, verbose_name='Nombre del proyecto')
    lugar = models.ForeignKey(Distrito,  on_delete=models.CASCADE, verbose_name='Ubicacion')
    direccion = models.CharField(max_length=50,  verbose_name='Direccion')
    google_maps = models.CharField(max_length=400, verbose_name='Google Maps', blank=True, null=True)
    tipo = models.CharField(max_length=50)
    precio_compra = models.FloatField()
    precio_venta = models.FloatField()
    observacion = models.CharField(max_length=50)
    fecha_creacion =models.DateTimeField(auto_now_add=True)
    fecha_modificado =models.DateTimeField(auto_now_add=True)
    

    class Meta:
        verbose_name = ("Proyecto")
        verbose_name_plural = ("Proyectos")

    def __str__(self):
        return self.nombre


class Sub_Proyecto(models.Model):

    class estados(models.TextChoices):

            VENDIDO = "VENDIDO"
            DISPONIBLE = "DISPONIBLE"
            SEPARADO = "SEPARADO"

    estado = models.CharField(choices=estados.choices, default="DISPONIBLE", max_length=20, verbose_name="Estado")
    proyecto = models.ForeignKey(Proyectos,  on_delete=models.CASCADE)
    nombre = models.CharField(max_length=50)
    direccion = models.CharField(max_length=50,  verbose_name='Direccion')
    m2 = models.IntegerField()
    precio_venta = models.IntegerField()
    plano = models.FileField(upload_to='plano/', verbose_name="Plano", blank=True, null=True)
    observacion = models.CharField(max_length=50)
    fecha_creacion =models.DateTimeField(auto_now_add=True)
    fecha_modificado =models.DateTimeField(auto_now_add=True)


    class Meta:
        verbose_name = ("Sub_Proyecto")
        verbose_name_plural = ("Sub_Proyectos")

  
    def __str__(self):
        return self.nombre

class Imagen(models.Model):
    sub_proyecto = models.ForeignKey(Sub_Proyecto, on_delete=models.CASCADE, related_name='imagenes')
    imagen = models.ImageField(verbose_name="Imagen", blank=True, null=True)

    class Meta:
        verbose_name = ("Imagen")
        verbose_name_plural = ("Imágenes")

    def __str__(self):
        return f"Imagen de {self.sub_proyecto.nombre}"

proyectos/forms.py
from django import forms
from .models import Proyectos ,Sub_Proyecto

class ProyectoForm(forms.ModelForm):
    class Meta:
        model = Proyectos
        fields = '__all__'  

    def __init__(self, *args, **kwargs):
        super(ProyectoForm, self).__init__(*args, **kwargs)

        self.fields['estado'].label = 'Estado'
        self.fields['nombre'].label = 'Nombre del Proyecto'
        self.fields['lugar'].label = 'Ubicación'
        self.fields['direccion'].label = 'Dirección'
        self.fields['google_maps'].label = 'Google Maps'
        self.fields['tipo'].label = 'Tipo'
        self.fields['precio_compra'].label = 'Precio de Compra'
        self.fields['precio_venta'].label = 'Precio de Venta'
        self.fields['observacion'].label = 'Observaciones'
     
        self.fields['estado'].widget.attrs['placeholder'] = 'Estado'
        self.fields['nombre'].widget.attrs['placeholder'] = 'Ingrese el nombre del proyecto'
        self.fields['direccion'].widget.attrs['placeholder'] = 'Ingrese la dirección del proyecto'
        self.fields['precio_compra'].widget.attrs['placeholder'] = 'Ingrese el precio de compra'
        self.fields['precio_venta'].widget.attrs['placeholder'] = 'Ingrese el precio de venta'
        
        self.fields['estado'].widget.attrs['class'] = 'form-control'
        self.fields['nombre'].widget.attrs['class'] = 'form-control'
        self.fields['direccion'].widget.attrs['class'] = 'form-control'
        self.fields['tipo'].widget.attrs['class'] = 'form-control'
        self.fields['precio_compra'].widget.attrs['class'] = 'form-control'
        self.fields['precio_venta'].widget.attrs['class'] = 'form-control'
        self.fields['observacion'].widget.attrs['class'] = 'form-control'
        
    
    def clean(self):
        cleaned_data = super().clean()
        precio_compra = cleaned_data.get('precio_compra')
        precio_venta = cleaned_data.get('precio_venta')
        
        if precio_compra and precio_venta:
            if precio_venta <= precio_compra:
                raise forms.ValidationError("El precio de venta debe ser mayor que el precio de compra.")
        return cleaned_data
    
    


class SubProyectoForm(forms.ModelForm):
    proyecto = forms.ModelChoiceField(queryset=Proyectos.objects.all(), empty_label="Seleccione un proyecto")
    
    class Meta:
        model = Sub_Proyecto
        fields = ['proyecto','nombre', 'direccion', 'm2', 'precio_venta', 'plano', 'observacion']
        widgets = {
            'plano': forms.FileInput(attrs={'accept': 'application/pdf,image/*'}),
        }
        
        
    def __init__(self, *args, **kwargs):
        super(SubProyectoForm, self).__init__(*args, **kwargs)

        self.fields['nombre'].label = 'Nombre'
        self.fields['direccion'].label = 'Direccion'
        self.fields['m2'].label = 'M2'
        self.fields['precio_venta'].label = 'Precio Venta'
        self.fields['plano'].label = 'Plano'
        self.fields['observacion'].label = 'Observacion'
        
        self.fields['nombre'].widget.attrs['placeholder'] = 'Nombre'
        self.fields['direccion'].widget.attrs['placeholder'] = 'Direccion'
        self.fields['m2'].widget.attrs['placeholder'] = 'M2'
        self.fields['precio_venta'].widget.attrs['placeholder'] = 'Precio Venta'
        self.fields['plano'].widget.attrs['placeholder'] = 'Plano'
        self.fields['observacion'].widget.attrs['placeholder'] = 'Pbservacion'
        
        self.fields['nombre'].widget.attrs['class'] = 'form-control'
        self.fields['direccion'].widget.attrs['class'] = 'form-control'
        self.fields['m2'].widget.attrs['class'] = 'form-control'
        self.fields['precio_venta'].widget.attrs['class'] = 'form-control'
        self.fields['plano'].widget.attrs['class'] = 'form-control'
        self.fields['observacion'].widget.attrs['class'] = 'form-control'

proyectos/views.py
from django.shortcuts import render
from .models import *
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from .forms import ProyectoForm, SubProyectoForm
from django.utils import timezone
from django.urls import reverse

# Create your views here.

def app_proyectos(request):
    return render(request, 'proyectos/app_proyectos.html')


def listar_proyectos(request):
    proyectos = Proyectos.objects.all()
    return render(request, 'proyectos/listar_proyectos.html' , {'proyectos': proyectos})

def crear_proyecto(request):
    if request.method == 'POST':
        form = ProyectoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('proyectos:listar_proyectos')
        
    else:
        form = ProyectoForm()
    return render(request, 'proyectos/crear_proyecto.html', {'form': form})

def ver_proyecto(request, pk):
    proyecto = get_object_or_404(Proyectos, id=pk)
    return render(request, 'proyectos/ver_proyecto.html', {'proyecto': proyecto})



def editar_proyecto(request, pk):
    proyecto = get_object_or_404(Proyectos, id=pk)
    if request.method == 'POST':
        form = ProyectoForm(request.POST, instance=proyecto)
        if form.is_valid():
            form.save()
            return redirect('proyectos:listar_proyectos')
    else:
        form = ProyectoForm(instance=proyecto)
    return render(request, 'proyectos/editar_proyecto.html', {'form': form})




def eliminar_proyecto(request, pk):  
    proyecto = get_object_or_404(Proyectos, id=pk)
    if request.method == 'POST':
        proyecto.delete()
        return redirect('proyectos:listar_proyectos')
    return render(request, 'proyectos/eliminar_proyecto.html', {'proyecto': proyecto})


 
    #subproyectos


def proyectos_y_subproyectos(request):
    proyectos = Proyectos.objects.all()
    proyecto_seleccionado = None
    subproyectos = None

    if 'proyecto_id' in request.GET:
        proyecto_id = request.GET['proyecto_id']
        proyecto_seleccionado = get_object_or_404(Proyectos, pk=proyecto_id)
        subproyectos = obtener_subproyectos(proyecto_seleccionado)  # Función para obtener subproyectos actualizados

    return render(request, 'proyectos/subproyectos/subproyectos.html', {'proyectos': proyectos, 'proyecto_seleccionado': proyecto_seleccionado, 'subproyectos': subproyectos})

def obtener_subproyectos(proyecto):
    return Sub_Proyecto.objects.filter(proyecto=proyecto)


def crear_subproyecto(request):
    if request.method == 'POST':
        form = SubProyectoForm(request.POST, request.FILES)
        if form.is_valid():
            subproyecto = form.save(commit=False)
            subproyecto.proyecto = form.cleaned_data['proyecto']  # Asigna el proyecto seleccionado al subproyecto
            subproyecto.save()
            return redirect('proyectos:subproyectos')
    else:
        form = SubProyectoForm()
    return render(request, 'proyectos/subproyectos/crear_subproyecto.html', {'form': form})

def actualizar_subproyecto(request, pk):
    subproyecto = get_object_or_404(Sub_Proyecto, id=pk)
    if request.method == 'POST':
        form = SubProyectoForm(request.POST, instance=subproyecto)
        if form.is_valid():
            form.save()
            return redirect('proyectos:subproyectos')
    else:
        form = SubProyectoForm(instance=subproyecto)
    return render(request, 'proyectos/subproyectos/actualizar_subproyecto.html', {'form': form})


def eliminar_subproyecto(request, pk):
    subproyecto = get_object_or_404(Sub_Proyecto, id=pk)
    
    if request.method == 'POST':
        subproyecto.delete()
        return redirect('proyectos:subproyectos')
    
    return render(request, 'proyectos/subproyectos/eliminar_subproyecto.html', {'subproyecto': subproyecto})

templates/proyectos/subproyectos/actualizar_subproyecto.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Actualizar Proyecto</title>
</head>
<body>
    <h1>Actualizar Proyecto</h1>
    <!-- Formulario para actualizar el proyecto -->
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar Cambios</button>
    </form>
</body>
</html>

templates/proyectos/subproyectos/crear_subproyecto.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear Subproyecto</title>
</head>
<body>
    <h1>Crear Subproyecto</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>
</body>
</html>

templates/proyectos/subproyectos/eliminar_subproyecto.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Eliminar Subproyecto</title>
</head>
<body>
    <h1>Eliminar Subproyecto</h1>
    <p>¿Estás seguro de que deseas eliminar el subproyecto "{{ subproyecto.nombre }}"?</p>
    <form action="" method="post">
        {% csrf_token %}
        <button type="submit">Sí, Eliminar</button>
        <a href="{% url 'proyectos:subproyectos' %}">Cancelar</a>
    </form>
</body>
</html>

templates/proyectos/subproyectos/subproyectos.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="page-wrapper">

    <div class="container-fluid">

        <div class="row page-titles">
            <div class="col-md-5 align-self-center">
                <h3 class="text-themecolor">Lista de Subproyectos</h3>
            </div>

            <div class="col-md-7 align-self-center">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="">Inicio</a></li>
                    <li class="breadcrumb-item"><a
                            href="">Panel</a>
                    </li>
                    <li class="breadcrumb-item">Lista</li>
                </ol>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body row">
                        <div class="col-12 justify-content-center">
        
                            <div class="row d-flex justify-content-center">
        
                                <div>
                
                                    <h4 class="card-title"><span class="lstick m-r-20"></span><b>Lista de subproyectos</b></h4>
                                    <h6 class="card-subtitle"></span>filtro de proyecto</h6>
                                </div>
        
                            </div>
                            <form method="get" class="mb-4">
                                <div class="form-group">
                                    <label for="proyecto">Selecciona un proyecto:</label>
                                    <select id="proyecto" name="proyecto_id" class="form-control">
                                        
                                        {% for proyecto in proyectos %}
                                            <option value="{{ proyecto.id }}" {% if proyecto_seleccionado and proyecto.id == proyecto_seleccionado.id %}selected{% endif %}>{{ proyecto.nombre }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <button type="submit" class="btn btn-primary">Filtrar</button>
                            </form>

                            <hr>
        
                            {% if subproyectos %}
                            <table id="users" class="table m-t-30 table-hover no-wrap contact-list" data-page-size="10">
                                <thead>
                                    <tr>
                                        <th>Estado</th>
                                        <th>Proyecto</th>
                                        <th>Nombre</th>
                                        <th>Dirección</th>
                                        <th>m2</th>
                                        <th>Precio de Venta</th>
                                        <th>Plano</th>
                                        <th>Observación</th>
                                        <th>Acciones</th>
                                    </tr>
                                </thead>
                                <tbody style="font-size: 14px; font-weight: 400;">
                                    {% for subproyecto in subproyectos %}
                                    <tr>
                                    
                                        {% if subproyecto.estado == "DISPONIBLE" %}
    
                                        <td style="text-primary"><b>{{subproyecto.estado}}</b>
                                         </td>
    
                                         {% else %}
    
                                        <td style="color: rgb(237, 30, 11)"><b>{{subproyecto.estado}}</b>
                                        </td>

                                         {% endif %}     
                                        <td>{{ subproyecto.proyecto.nombre }}</td>
                                        <td>{{ subproyecto.nombre }}</td>
                                        <td>{{ subproyecto.direccion }}</td>
                                        <td>{{ subproyecto.m2 }}</td>
                                        <td>{{ subproyecto.precio_venta }}</td>
                                    
                                        <td style="text-align: center;"><a href="{{ subproyecto.plano.url }}" target="_blank"><i
                                            class="fa fa-file-pdf-o text-danger"></i></a></td>
                                        <td>{{ subproyecto.observacion }}</td>

                                        <td>
                                                        

                                            <a href="{% url 'proyectos:actualizar_subproyecto' subproyecto.pk %}">
                                                <i class="fa fa-edit" style="color: blue;"></i>
                                            </a> 

                                            <a href="{% url 'proyectos:eliminar_subproyecto' subproyecto.pk %}">
                                                <i class="fa fa-trash" style="color: red; margin-left: 5px;"></i>
                                            </a>
                                        </td>
                                    </tr>
                                    {% endfor %}

                                </tbody>
                            </table>
                            {% else %}
                            <p>No hay subproyectos disponibles.</p>
                            {% endif %}
        
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <style>
            .img-activo {
                margin-left: -10px;
                border: 2px solid #72BE53;
            }
    
            .img-desactivado {
                margin-left: -10px;
                border: 2px solid #BE5653;
            }
    
            #add {
                position: fixed;
                bottom: 60px;
                right: 20px;
                animation: scale 1.2s infinite;
            }
        </style>
    
        <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    
        <script>
            $(document).ready(function () {
                $('#users').DataTable({
                    "language": {
                        "lengthMenu": "Mostar _MENU_ documentos",
                        "zeroRecords": "Sin coincidencias",
                        "info": "Pagina _PAGE_ de _PAGES_",
                        "infoEmpty": "Sin registros disponibles",
                        "infoFiltered": "(filtrado de _MAX_ registros totales)",
                        "search": "Buscar"
                    },
    
                    "ordering": false,
                    "info": false,
                    "paging": false,
                });
            });
        </script>
    </div>

    <a id="add" href="{% url 'proyectos:crear_subproyecto' %}" data-toggle="tooltip" data-placement="left" title="Crear nuevo subproyecto" class="btn btn-info btn-circle fa fa-plus"></a>

   

    <!-- Termina accesos directos -->

    <a href="" style="text-decoration: none;">
        <footer class="footer">© Link-P</footer>
    </a>
    </div>
</div>


{% endblock %}