clientes/urls.py
from django.urls import path
from . import views
from .views import *


app_name="clientes"

urlpatterns = [
   
    # Your URL patterns here
    path('clientes_panel/', views.app_clientes, name='clientes_panel'),
    path('clientes/', views.clientes, name='clientes'),
    
    path('crear/', views.crear_cliente, name='crear_cliente'),
    path('ver/<int:pk>/', views.ver_cliente, name='ver_cliente'),
    
    path('editar_cliente/<str:pk>/', views.editar_cliente, name='editar_cliente'),
    path('eliminar/<str:pk>/', views.eliminar_cliente, name='eliminar_cliente'),

    #SEPARAR LOTES
    path('ventas/', views.listar_ventas, name='listar_ventas'),
    path('ventas/crear/', views.crear_venta, name='crear_venta'),
    path('ventas/<int:venta_id>/', views.ver_venta, name='ver_venta'),
    path('ventas/<int:venta_id>/actualizar/', views.actualizar_venta, name='actualizar_venta'),
    path('ventas/<int:venta_id>/eliminar/', views.eliminar_venta, name='eliminar_venta'),

    #cuotas
    path('listar_cuotas/', views.listar_cuotas, name='lista_cuotas'),
    path('crear_cuota/', views.crear_cuota, name='crear_cuota'),
    path('detalle_venta/<int:pk>/', views.detalle_cuota, name='detalle_cuota'),
]

core/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('usuarios.urls', namespace='usuarios')),
    path('clientes/', include('clientes.urls', namespace='clientes')),
    path('finanzas/', include('finanzas.urls', namespace='finanzas')),
    path('proyectos/', include('proyectos.urls', namespace='proyectos')),
    path('reportes/', include('reportes.urls', namespace='reportes')),
    path('rrhh/', include('rrhh.urls', namespace='rrhh')),
    path('socios/', include('socios.urls', namespace='socios')),
    path('web/', include('web.urls', namespace='web')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

finanzas/urls.py
from django.urls import path
from . import views
from .views import *

app_name="finanzas"

urlpatterns = [
   
    path('finanzas_panel/', views.app_finanzas, name='finanzas_panel'),
]

rrhh/urls.py
from django.urls import path
from . import views
from .views import *

app_name="rrhh"

urlpatterns = [
   
    path('reportes_rrhh/', views.app_rrhh, name='rrhh_panel'),
]

socios/urls.py
from django.urls import path
from . import views
from .views import *

app_name="socios"

urlpatterns = [
   
    path('socios_panel/', views.app_socios, name='socios_panel'),
]

web/urls.py
from django.urls import path
from . import views
from .views import *    


app_name="web"

urlpatterns = [
   
    path('web/', views.appWeb, name = 'web'),
    path('listar/', views.listar, name = 'listarCompras'),
    path('separarLote/', views.separar_lote , name = 'separarLote'),
    path('pag_web/', views.pag_web, name = 'pag_web'),

    
]
    

templates/base.html
{% load static %}
{% load tags_extras %}

<!DOCTYPE html>
<html lang="es">

<head>
  <meta charset="UTF-8">

  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="shortcut icon" href="{% static 'img/LinkIco21.ico' %}" />
  <link rel="text/html" href="extensions/sticky-header/bootstrap-table-sticky-header.css">
  <link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css">
  <link rel="stylesheet" href="{% static 'css/bootstrap5.min.css' %}">
  <link rel="stylesheet" href="../../static/css/registro_contable.css">
  <link href="{% static 'adminpro/assets/plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/inicio.css' %}">

  {% include 'includes/css/chartlist.html' %}
  {% include 'includes/css/form.html' %}
  {% include 'includes/css/datatable.html' %}
  {% include 'includes/css/otros.html' %}

  <title>Monaco</title>

</head>


<body>
  <div class="preloader">
    <div class="loader">
      <div class="loader__figure"></div>
      <p class="loader__label">anuncios</p>
    </div>
  </div>

  <div id="main-wrapper">
    <header class="topbar">
      <nav class="navbar top-navbar navbar-expand-md navbar-light">
        <div class="navbar-header" id="navbar">
          <a class="navbar-brand" href="/inicio">
            <b>
              <img src="{% static 'img/IconoP.png' %}"
                style="max-width: 55px; vertical-align: bottom; margin-bottom: 12px;" alt="homepage" class="dark-logo"
                id="dark-logo" />
              <img src="{% static 'img/linkpblancoC.png' %}"
                style="max-width: 55px; vertical-align: bottom; margin-top: 12px; margin-bottom: 0px;" alt="homepage"
                class="light-logo" id="light-logo" />
            </b>
            <span>
              <img src="{% static 'img/Linkp.png' %}"
                style="max-width: 80px; vertical-align: bottom; margin-bottom: 12px;" alt="homepage"
                class="dark-logo" />
              <img src="{% static 'img/Linkp.png' %}"
                style="max-width: 80px; vertical-align: bottom; margin-bottom: 12px;" alt="homepage"
                class="light-logo" />
            </span>
          </a>
        </div>

        <div class="navbar-collapse">
          <ul class="navbar-nav mr-auto">

            <li class="nav-item"> <a class="nav-link nav-toggler hidden-md-up waves-effect waves-dark"
                href="javascript:void(0)"><i class="ti-menu"></i></a> </li>
            <li class="nav-item"> <a class="nav-link sidebartoggler hidden-sm-down waves-effect waves-dark"
                href="javascript:void(0)"><i class="ti-menu"></i></a> </li>

          </ul>



          <ul class="navbar-nav my-lg-0" style="margin-left: 5px;">
            <li>
              <a class="nav-link waves-effect waves-dark" href="/rrhh/notasdepedido/0/0">
                <i class="fa fa-lg fa-envelope-o text-light" id="notaspedido">
                </i>
              </a>
              <div class="notify"><span class="heartbit"></span> <span class="point"></span></div>
            </li>
          </ul>





          <ul class="navbar-nav my-lg-0" style="margin-left: 5px;">

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle waves-effect waves-dark" href="" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false"> <img src="{% static 'img/acuerdos2.png' %}" alt=""
                  width="30px" id="acuerdos">
                <div class="notify"><span class="heartbit"></span> <span class="point"></span></div>
              </a>
              <div class="dropdown-menu dropdown-menu-right mailbox animated bounceInDown">
                <ul>
                  <li>
                    <div class="drop-title">Acuerdos pendientes catidad</div>
                  </li>
                  <li>
                    <div class="message-center">


                      <a href="">

                        <div class="btn btn-success btn-circle"><i class="ti-calendar"></i></div>

                        <div class="btn btn-danger btn-circle"><i class="fa fa-link"></i></div>

                        <div class="mail-contnet">
                          <h5>minuta nombre</h5> <span class="mail-desc"> </span>
                        </div>
                      </a>



                    </div>
                  </li>
                  <li>
                    <a class="nav-link text-center" href=""> <strong>Ir al panel de
                        minutas</strong> <i class="fa fa-angle-right"></i> </a>
                  </li>
                </ul>
              </div>
            </li>
          </ul>


          <ul class="navbar-nav my-lg-0" style="margin-left: 5px;">
            <li>
              <a class="nav-link waves-effect waves-dark" href=""><img src="{% static 'img/acuerdos2.png' %}" alt=""
                  width="30px" id="minutas"></a>

            </li>
          </ul>


          <ul class="navbar-nav my-lg-0" style="margin-left: 5px;">

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle waves-effect waves-dark" href="" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false"> <img src="" alt="" width="30px" id="OC">
                <div class="notify"><span class="heartbit"></span> <span class="point"></span></div>
              </a>
              <div class="dropdown-menu dropdown-menu-right mailbox animated bounceInDown">
                <ul>
                  <li>
                    <div class="drop-title">



                    </div>
                  </li>
                  <li>

                    <div class="message-center">



                      <a href="">

                        <div class="btn btn-info btn-circle" style="margin-right: 5px;"></div>
                        <div class="mail-contnet">
                          <h5></h5> <span class="mail-desc"></span>
                        </div>

                      </a>


                      <a href="">

                        <div class="btn btn-warning btn-circle" style="margin-right: 5px;"></div>
                        <div class="mail-contnet">
                          <h5></h5> <span class="mail-desc"></span>
                        </div>

                      </a>



                    </div>
                  </li>
                  <li>
                    <a class="nav-link text-center" href=""> <strong>Solicitudes de
                        compra</strong> <i class="fa fa-angle-right"></i> </a>
                  </li>


                  <div class="message-center">



                    <a href="">

                      <div class="btn btn-info btn-circle" style="margin-right: 5px;"></div>
                      <div class="mail-contnet">
                        <h5></h5> <span class="mail-desc"></span>
                      </div>

                    </a>



                    <a href="">

                      <div class="btn btn-info btn-circle" style="margin-right: 5px;"></div>
                      <div class="mail-contnet">
                        <h5></h5> <span class="mail-desc"></span>
                      </div>

                    </a>



                  </div>
            </li>
            <li>
              <a class="nav-link text-center" href=""> <strong>Solicitudes de
                  compra</strong> <i class="fa fa-angle-right"></i> </a>
            </li>


            <div class="message-center">



              <a href="">

                <div class="btn btn-red btn-circle" style="margin-right: 5px;"><img src="" width="35"></div>
                <div class="mail-contnet">
                  <h5></h5> <span class="mail-desc"></span>
                </div>

              </a>



              <a href="">

                <div class="btn btn-warning btn-circle" style="margin-right: 5px;"><img src="" width="35"
                    class="img-circle"></div>
                <div class="mail-contnet">
                  <h5></h5> <span class="mail-desc"></span>
                </div>

              </a>



            </div>
            </li>
            <li>
              <a class="nav-link text-center" href=""> <strong>Solicitudes de
                  compra</strong> <i class="fa fa-angle-right"></i> </a>
            </li>


          </ul>
        </div>
        </li>
        </ul>


        <ul class="navbar-nav my-lg-0" style="margin-left: 5px;" id="chanchito-guia">
          <li>
            <a class="nav-link waves-effect waves-dark" href=""><img src="{% static 'img/pig.png' %}" alt=""
                width="30px"></a>

          </li>
        </ul>

        <ul class="navbar-nav my-lg-0" style="margin-left: 5px;" id="sugerencias-guia">
          <li>
            <a class="nav-link waves-effect waves-dark" href=""><img src="" alt="" width="30px"></a>

          </li>
        </ul>
      </nav>
    </header>
  </div>

  <aside class="left-sidebar">
    <div class="scroll-sidebar">


      <nav class="sidebar-nav" id="sidebar-guia">
        <ul id="sidebarnav">

          <li class="user-profile" id="perfilusuario-guia">

            <a class="has-arrow waves-effect waves-dark" href="#" aria-expanded="false"><img
                src="{{ request.user.username|logo }}" alt="user" /><span
                class="hide-menu">{{user.user_name}}</span></a>

            <ul aria-expanded="false" class="collapse">
              <li><a href="">Mi perfil</a></li>

              <li><a href="">Informes</a></li>

              <li><a href="/logout">Logout</a></li>
            </ul>
          </li>
          <li><a href="{% url 'rrhh:rrhh_panel' %}"><i class="mdi mdi-chart-bubble"></i><span class="hide-menu">Recursos
                Humanos</span></a>
          </li>
          <li class="nav-small-cap">ESPACIOS DE TRABAJO</li>
          <li class="nav-devider"></li>

          <!--  <li><a href=""><i class="zmdi zmdi-accounts"></i><span class="hide-menu"></span></a>   -->
          </li>
          <li><a href="{% url 'proyectos:proyectos' %}"><i class="zmdi zmdi-chart"></i><span
                class="hide-menu">Proyectos</span></a>
          </li>

          <li><a href="{% url 'clientes:clientes_panel' %}"><i class="zmdi zmdi-file "></i><span
                class="hide-menu">clientes</span></a>
          </li>

          <li><a href="{% url 'socios:socios_panel' %}"><i class="zmdi zmdi-file "></i><span
                class="hide-menu">Socios</span></a>
          </li>
          <li><a href="{% url 'finanzas:finanzas_panel' %}"><i class="zmdi zmdi-file "></i><span
                class="hide-menu">Finanzas</span></a>
          </li>

          <li><a href="{% url 'reportes:reportes_panel' %}"><i class="zmdi zmdi-card"></i><span
                class="hide-menu">Reportes</span></a>
          </li>


          <li class="user-profile" id="perfilusuario-guia">

            <a class="has-arrow waves-effect waves-dark" href="#" aria-expanded="false"><i class="zmdi zmdi-mall"></i>
              <span class="hide-menu">Web
                inmobiliaria</span></a>

            <ul aria-expanded="false" class="collapse">
              <li>
                <a href="{% url 'web:listarCompras' %}">
                  <span class="hide-menu">Separaciones de la web</span></a>
              </li>

              <li>
                <a href="{% url 'web:pag_web' %}">Pagina web</a>
              </li>

              <li>
                <a href="#">Agregar Terreno</a>
              </li>

            </ul>
          </li>

          <li><a href=""><i class="zmdi zmdi-calendar"></i><span class="hide-menu">CONFIG</span></a>
          </li>

        </ul>

      </nav>
    </div>
  </aside>


  {% block content %}

  {% endblock content %}




  <script src="{% static 'adminpro/main/js/perfect-scrollbar.jquery.min.js' %}"></script>
  <script src="{% static  'js/dataTables.bootstrap4.min.js' %}"></script>

  <style>
    #pulse:hover {
      transform: scale(1.05);

    }

    .img-profile {
      margin-left: -10px;
      border: 2px solid #AFAFB4;
    }
  </style>

  <script>
    function guia() {
      let sidebar = document.getElementById('sidebar-guia');
      sidebar.classList.add('alerta-guia-borde');
      let alertaguia1 = document.getElementById('alerta-guia-1').style.display = "block";

    }
    function guia1(cerrar, abrir, idcerrar, idabrir) {
      console.log(cerrar, abrir, idcerrar, idabrir);
      let sidebar = document.getElementById(idcerrar);
      sidebar.classList.remove('alerta-guia-borde');
      let alertaguia1 = document.getElementById(cerrar).style.display = "none";
      let guiausuario = document.getElementById(idabrir);
      guiausuario.classList.add('alerta-guia-borde');
      let alertaguia2 = document.getElementById(abrir).style.display = "block";

    }
    function finalizar(resaltado, id) {
      let sidebar = document.getElementById(resaltado);
      sidebar.classList.remove('alerta-guia-borde');
      let modalcerrar = document.getElementById(id).style.display = "none";

    }



  </script>






  <script src="{% static 'js/jquery-3.5.1.js' %}"></script>
  <script src="{% static 'adminpro/assets/plugins/bootstrap/js/popper.min.js' %}"></script>
  <script src="{% static 'adminpro/assets/plugins/bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'adminpro/main/js/sidebarmenu.js' %}"></script>
  <script src="{% static 'adminpro/main/js/dashboard1.js' %}"></script>
  <script src="{% static 'adminpro/main/js/custom.min.js' %}"></script>
  <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>


  {% include 'includes/js/datatable.html' %}
  {% include 'includes/js/chartlist.html' %}
  {% include 'includes/js/form.html' %}
  {% include 'includes/js/otros.html' %}




</body>

</html>