clientes/urls.py
from django.urls import path
from . import views
from .views import *


app_name="clientes"

urlpatterns = [
   
    # Your URL patterns here
    path('clientes_panel/', views.app_clientes, name='clientes_panel'),
    path('clientes/', views.clientes, name='clientes'),
    
    path('crear/', views.crear_cliente, name='crear_cliente'),
    path('ver/<int:pk>/', views.ver_cliente, name='ver_cliente'),
    
    path('editar_cliente/<str:pk>/', views.editar_cliente, name='editar_cliente'),
    path('eliminar/<str:pk>/', views.eliminar_cliente, name='eliminar_cliente'),

    #SEPARAR LOTES
    path('ventas/', views.listar_ventas, name='listar_ventas'),
    path('ventas/crear/', views.crear_venta, name='crear_venta'),
    path('ventas/<int:venta_id>/', views.ver_venta, name='ver_venta'),
    path('ventas/<int:venta_id>/actualizar/', views.actualizar_venta, name='actualizar_venta'),
    path('ventas/<int:venta_id>/eliminar/', views.eliminar_venta, name='eliminar_venta'),

    #cuotas
    path('listar_cuotas/', views.listar_cuotas, name='lista_cuotas'),
    path('crear_cuota/', views.crear_cuota, name='crear_cuota'),
    path('detalle_venta/<int:pk>/', views.detalle_cuota, name='detalle_cuota'),
]

core/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('usuarios.urls', namespace='usuarios')),
    path('clientes/', include('clientes.urls', namespace='clientes')),
    path('finanzas/', include('finanzas.urls', namespace='finanzas')),
    path('proyectos/', include('proyectos.urls', namespace='proyectos')),
    path('reportes/', include('reportes.urls', namespace='reportes')),
    path('rrhh/', include('rrhh.urls', namespace='rrhh')),
    path('socios/', include('socios.urls', namespace='socios')),
    path('web/', include('web.urls', namespace='web')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

proyectos/urls.py
from django.urls import path
from . import views
from .views import *


app_name="proyectos"

urlpatterns = [
   
    path('proyectos/', views.app_proyectos, name = 'proyectos'),

    path('listar/', views.listar_proyectos, name='listar_proyectos'),
    path('crear/', views.crear_proyecto, name='crear_proyecto'),
    path('ver/<int:pk>/', views.ver_proyecto, name='ver_proyecto'),
    
    path('editar_empleado/<str:pk>/', views.editar_proyecto, name='editar_proyecto'),
    path('eliminar/<str:pk>/', views.eliminar_proyecto, name='eliminar_proyecto'),
    
    # Subproyectos
    path('subproyectos', views.proyectos_y_subproyectos, name='subproyectos'),    
    path('subproyectos/crear/', views.crear_subproyecto, name='crear_subproyecto'),
    path('subproyectos/<str:pk>/', views.actualizar_subproyecto, name='actualizar_subproyecto'),
    path('subproyectos/<str:pk>/eliminar', views.eliminar_subproyecto, name='eliminar_subproyecto'),
    

 

    
]

usuarios/urls.py
from django.urls import path
from . import views
from .views import *

app_name="usuarios"

urlpatterns = [
    path('', views.welcome, name="welcome"),
    path('login/', views.login, name="login"),
    path('home/', HomeView.as_view(), name="home"),
    path('logout', views.logout, name = 'Logout'),

    
    
    # Your URL patterns here
]

web/urls.py
from django.urls import path
from . import views
from .views import *    


app_name="web"

urlpatterns = [
   
    path('web/', views.appWeb, name = 'web'),
    path('listar/', views.listar, name = 'listarCompras'),
    path('separarLote/', views.separar_lote , name = 'separarLote'),
    path('pag_web/', views.pag_web, name = 'pag_web'),

    
]
    

clientes/models.py
from django.db import models
from datetime import timedelta
from django.db.models.signals import pre_save, post_save
from proyectos.models import *
from django.dispatch import receiver

class Cliente(models.Model):

    nombres = models.CharField(max_length=100)
    ap_paterno  = models.CharField(max_length=100)
    ap_materno = models.CharField(max_length=100)
    direccion = models.CharField(max_length=100)
    documento = models.IntegerField()
    celular = models.IntegerField()
    fecha_creacion =models.DateTimeField(auto_now_add=True)
    fecha_modificado =models.DateTimeField(auto_now_add=True)
    

    class Meta:
        verbose_name = ("Cliente")
        verbose_name_plural = ("Clientes")

    def __str__(self):
        return self.nombres


class Venta(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE, related_name='ventas')
    proyecto = models.ForeignKey(Proyectos, on_delete=models.CASCADE, related_name='ventas', blank=True, null=True)
    subproyecto = models.ForeignKey(Sub_Proyecto, on_delete=models.CASCADE, related_name='ventas')
    precio_venta = models.FloatField()
    forma_pago = models.CharField(max_length=20, choices=[('contado', 'Contado'), ('cuotas', 'Cuotas')])
    cuotas = models.IntegerField(verbose_name="Cuotas", default=1, null=False)
    fecha_creacion =models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.subproyecto.estado = 'SEPARADO'
        self.subproyecto.save()
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = ("Venta")
        verbose_name_plural = ("Ventas")

    def __str__(self):
        return f"Venta de {self.subproyecto.nombre} del proyecto {self.proyecto.nombre} a {self.cliente.nombres}"
    
@receiver(pre_save, sender=Venta)
def actualizar_precio_venta(sender, instance, **kwargs):
   
    instance.precio_venta = instance.subproyecto.precio_venta
    instance.proyecto = instance.subproyecto.proyecto

@receiver(pre_save, sender=Venta)
def verificar_subproyecto(sender, instance, **kwargs):
    if instance.subproyecto.ventas.exists():
        raise ValueError('Este subproyecto ya está asociado a una venta')


class Cuota(models.Model):
    ESTADO_CHOICES = (
        ('pendiente', 'Pendiente'),
        ('pagado', 'Pagado')
    )

    venta = models.ForeignKey('clientes.Venta', on_delete=models.CASCADE)
    monto = models.DecimalField(max_digits=10, decimal_places=2)
    fecha_vencimiento = models.DateField()
    estado_pago = models.CharField(max_length=20, choices=ESTADO_CHOICES, default='pendiente')
    fecha_pago = models.DateField(null=True, blank=True)

    def __str__(self):
        return f"Cuota de {self.venta} - Monto: {self.monto} - Fecha de Vencimiento: {self.fecha_vencimiento}"

@receiver(post_save, sender='clientes.Venta')
def generar_cuotas(sender, instance, created, **kwargs):
    if created:

        precio_venta = instance.precio_venta
        cantidad_cuotas = instance.cuotas


        monto_cuota = min(instance.precio_venta / cantidad_cuotas, instance.precio_venta)

        fecha_vencimiento = instance.fecha_creacion.date() + timedelta(days=30)  

        for _ in range(cantidad_cuotas):
            Cuota.objects.create(
                venta=instance,
                monto=monto_cuota,
                fecha_vencimiento=fecha_vencimiento
            )
            fecha_vencimiento += timedelta(days=30)  


class Cobro(models.Model):
    venta = models.ForeignKey(Venta, on_delete=models.CASCADE)
    monto = models.DecimalField(max_digits=10, decimal_places=2)
    fecha = models.DateField()
    

    def __str__(self):
        return f"Cobro de {self.monto} para la venta {self.venta}"
    

clientes/forms.py
from django import forms
from .models import *

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = '__all__'  

    def __init__(self, *args, **kwargs):
        super(ClienteForm, self).__init__(*args, **kwargs)

        self.fields['nombres'].label = 'Nombres'
        self.fields['ap_paterno'].label = 'Apellido Paterno'
        self.fields['ap_materno'].label = 'Apellido Materno'
        self.fields['direccion'].label = 'Dirección'
        self.fields['documento'].label = 'Documento'
        self.fields['celular'].label = 'Celular'
       
       
       
        self.fields['nombres'].widget.attrs['placeholder'] = 'Nombres'
        self.fields['ap_paterno'].widget.attrs['placeholder'] = 'Apellido Paterno'
        self.fields['ap_materno'].widget.attrs['placeholder'] = 'Apellido Materno'
        self.fields['direccion'].widget.attrs['placeholder'] = 'Dirección'
        self.fields['documento'].widget.attrs['placeholder'] = 'Documento'
        self.fields['celular'].widget.attrs['placeholder'] = 'Celular'


        self.fields['nombres'].widget.attrs['class'] = 'form-control'
        self.fields['ap_paterno'].widget.attrs['class'] = 'form-control'
        self.fields['ap_materno'].widget.attrs['class'] = 'form-control'
        self.fields['direccion'].widget.attrs['class'] = 'form-control'
        self.fields['documento'].widget.attrs['class'] = 'form-control'
        self.fields['celular'].widget.attrs['class'] = 'form-control'
     


class VentaForm(forms.ModelForm):
    class Meta:
            model = Venta
            fields = ['cliente', 'proyecto', 'subproyecto', 'precio_venta', 'forma_pago', 'cuotas']
   
    
    def __init__(self, *args, **kwargs):
        proyecto_id = kwargs.pop('proyecto_id', None)
        super().__init__(*args, **kwargs)
        if proyecto_id:
            self.fields['subproyecto'].queryset = Sub_Proyecto.objects.filter(proyecto_id=proyecto_id)

        self.fields['cuotas'].required = False  

        if 'forma_pago' in self.data:
            forma_pago = self.data['forma_pago']
        elif self.instance.pk:
            forma_pago = self.instance.forma_pago
        else:
            forma_pago = None
        
        if forma_pago == 'contado':
            self.fields['cuotas'].widget = forms.HiddenInput()  
            self.fields['cuotas'].label = ''  
            self.initial['cuotas'] = 1  
        
        




class CuotaForm(forms.ModelForm):
    class Meta:
        model = Cuota
        fields = '__all__' 
        widgets = {
            'fecha_vencimiento': forms.DateInput(attrs={'type': 'date'}),
            'fecha_pago': forms.DateInput(attrs={'type': 'date'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['monto'].widget.attrs['step'] = '0.01'

clientes/views.py
from django.shortcuts import render, redirect
from .models import Cliente
from django.shortcuts import get_object_or_404
from .forms import *
from django.views.generic import ListView, CreateView


def app_clientes(request):
    return render(request, 'clientes/app_clientes.html')

def clientes(request):
    lista_clientes = Cliente.objects.all()
    data = {
        'lista_clientes' :lista_clientes,
    }
    return render(request, 'clientes/clientes.html', data)


def crear_cliente(request):
    if request.method == 'POST':
        form = ClienteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('clientes:clientes')
        
    else:
        form = ClienteForm()
    return render(request, 'clientes/crear_cliente.html', {'form': form})

def ver_cliente(request, pk):
    cliente = get_object_or_404(Cliente, id=pk)
    return render(request, 'clientes/ver_cliente', {'cliente': cliente})



def editar_cliente(request, pk):
    cliente = get_object_or_404(Cliente, id=pk)
    if request.method == 'POST':
        form = ClienteForm(request.POST, instance=cliente)
        if form.is_valid():
            form.save()
            return redirect('clientes:clientes')
    else:
        form = ClienteForm(instance=cliente)
    return render(request, 'clientes/editar_cliente.html', {'form': form})




def eliminar_cliente(request, pk):  
    cliente = get_object_or_404(Cliente, id=pk)
    if request.method == 'POST':
        cliente.delete()
        return redirect('clientes:listar_proyectos')
    return render(request, 'clientes/eliminar_cliente.html', {'cliente': cliente})





# SEPARAR LOTES



def listar_ventas(request):
    ventas = Venta.objects.all()
    return render(request, 'clientes/lotes/lista_ventas.html', {'ventas': ventas})

def crear_venta(request):
    if request.method == 'POST':
        form = VentaForm(request.POST)
        if form.is_valid():
            try:
                venta = form.save(commit=False)
                venta.cuotas = form.cleaned_data['cuotas']  # Obtener las cuotas del formulario
                venta.save()

                subproyecto = venta.subproyecto
                subproyecto.estado = 'SEPARADO'
                subproyecto.save()
                return redirect('clientes:listar_ventas')
            except ValueError as e:
                error_message = str(e)
                return render(request, 'clientes/lotes/crear_venta.html', {'form': form, 'error_message': error_message})
    else:
        proyecto_id = request.GET.get('proyecto')
        form = VentaForm(proyecto_id=proyecto_id)  # Pasa el ID del proyecto al formulario

    return render(request, 'clientes/lotes/crear_venta.html', {'form': form})



def ver_venta(request, venta_id):
    venta = get_object_or_404(Venta, pk=venta_id)
    return render(request, 'clientes/lotes/ver_venta.html', {'venta': venta})

def actualizar_venta(request, venta_id):
    venta = get_object_or_404(Venta, pk=venta_id)
    if request.method == 'POST':
        form = VentaForm(request.POST, instance=venta)
        if form.is_valid():
            form.save()
            return redirect('listar_ventas')
    else:
        form = VentaForm(instance=venta)
    return render(request, 'clientes/lotes/actualizar_venta.html', {'form': form})

def eliminar_venta(request, venta_id):
    venta = get_object_or_404(Venta, pk=venta_id)
    if request.method == 'POST':
        venta.delete()
        return redirect('listar_ventas')
    return render(request, 'clientes/lotes/confirmar_eliminar_venta.html', {'venta': venta})


# cuotas

def listar_cuotas(request):
    cuotas = Cuota.objects.all()
    return render(request, 'clientes/cuotas/lista_cuotas.html', {'cuotas': cuotas})

def crear_cuota(request):
    if request.method == 'POST':
        form = CuotaForm(request.POST)
        if form.is_valid():
            cuota = form.save()
            return redirect('clientes:detalle_cuota', pk=cuota.venta.pk)  
    else:
        form = CuotaForm()
    return render(request, 'clientes/cuotas/crear_cuota.html', {'form': form})


def detalle_cuota(request, pk):
    venta = Venta.objects.get(pk=pk)
    cuotas = Cuota.objects.filter(venta=venta)
    return render(request, 'clientes/cuotas/detalle_cuota.html', {'venta': venta, 'cuotas': cuotas})

templates/clientes/clientes.html
{% extends "base.html" %}
{% load static %}
{% load tags_extras %}

{% block content %}

<div class="page-wrapper">
    <!-- Empieza accesos directos -->
    <div class="container-fluid">
        <div class="row page-titles">
            <div class="col-md-5 align-self-center">
                <h3 class="text-themecolor">Lista de Clientes</h3>
            </div>
            <div class="col-md-7 align-self-center">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="">Inicio</a></li>
                    <li class="breadcrumb-item"><a href="">Panel</a></li>
                    <li class="breadcrumb-item">Clientes</li>
                </ol>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-11">
                                <h4 class="card-title"><span class="lstick m-r-20"></span>Proyectos</h4>
                            </div>
                        </div>
                        <div class="table-responsive">
                            <table id="users" class="table m-t-30 table-hover no-wrap contact-list" data-page-size="10">
                                <thead>
                                    <tr>
                                        <th>Nombres</th>
                                        <th>Apellido Paterno</th>
                                        <th>Apellido Materno</th>
                                        <th>Dirección</th>
                                        <th>Documento</th>
                                        <th>Nro. Celular</th>
                                        <th>Acciones</th>
                                   
                                    </tr>
                                </thead>
                                <tbody style="font-size: 14px; font-weight: 400;">
                                    {% for cliente in lista_clientes %}
                                    <tr>
                                      
                                        <td>{{ cliente.nombres }}</td>
                                        <td>{{ cliente.ap_paterno }}</td>
                                        <td>{{ cliente.ap_materno }}</td>
                                        <td>{{ cliente.direccion }}</td>
                                        <td>{{ cliente.documento }}</td>
                                        <td>{{ cliente.celular }}</td>                                    
                                       
                                        <td>
                                            

                                            <a href="{% url 'clientes:editar_cliente' cliente.pk %}">
                                                <i class="fa fa-edit" style="color: blue;"></i>
                                            </a> 

                                            <a href="{% url 'clientes:eliminar_cliente' cliente.pk %}">
                                                <i class="fa fa-trash" style="color: red; margin-left: 5px;"></i>
                                            </a>
                                        </td>
                                       
                                    </tr>

                                    
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


   

    <a id="add" href="{% url 'clientes:crear_cliente' %}" data-toggle="tooltip" data-placement="left" title="Crear nuevo proyecto" class="btn btn-info btn-circle fa fa-plus"></a>

    <style>
        .img-activo {
            margin-left: -10px;
            border: 2px solid #72BE53;
        }

        .img-desactivado {
            margin-left: -10px;
            border: 2px solid #BE5653;
        }

        #add {
            position: fixed;
            bottom: 60px;
            right: 20px;
            animation: scale 1.2s infinite;
        }
    </style>

    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>

    <script>
        $(document).ready(function () {
            $('#users').DataTable({
                "language": {
                    "lengthMenu": "Mostar _MENU_ documentos",
                    "zeroRecords": "Sin coincidencias",
                    "info": "Pagina _PAGE_ de _PAGES_",
                    "infoEmpty": "Sin registros disponibles",
                    "infoFiltered": "(filtrado de _MAX_ registros totales)",
                    "search": "Buscar"
                },

                "ordering": false,
                "info": false,
                "paging": false,
            });
        });
    </script>

    <!-- Termina accesos directos -->

    <a href="" style="text-decoration: none;">
        <footer class="footer">© Link-P</footer>
    </a>
</div>



{% endblock content %}

templates/clientes/crear_cliente.html
{% extends "base.html" %}

{% load static %}
{% load tags_extras %}


    {% block content %}

    
    <div class="page-wrapper">
  

  

        <!-- empieza accesos directos -->

        <div class="container-fluid r-aside">
            <div class="row page-titles">
                <div class="col-md-5 align-self-center">
                    <h3 class="text-themecolor">Crear Cliente</h3>
                </div>
        
                <div class="col-md-7 align-self-center">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'usuarios:home' %}">Inicio</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'proyectos:proyectos' %}">Panel</a></li>
                        <li class="breadcrumb-item">cliente</li>
                    </ol>
                </div>
            </div>
        
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body row">
                            <div class="col-12 justify-content-center">
        
                                <div class="row d-flex justify-content-center">
                                    <div class="col col-md-12 col-lg-10">
                                        <div class="row">
                                            <div class="col bg-light border rounded p-3">

                                                <form role="form" enctype="multipart/form-data" action="" method="POST" id="upload-image-form" class="p-4">
                                                    {% csrf_token %}
                                                    <h4 class="mb-3">Panel de creación</h4>
                                                    <hr>

                                                    
                                                
                                                    <div class="row d-flex">

                                                        <div class="col-lg-4 col-md-4  my-3 row-sm">
                                                            <label for="{{ form.nombres.id_for_label }}">
                                                                <h6>{{ form.nombres.label }}</h6>
                                                            </label>
                                                            <div class="row d-flex justify-content-center">
                                                                <div class="">
                                                                    {{ form.nombres }}
                                                                </div>
                                                            </div>
                                                        </div>

                                                        <div class="col-lg-4 col-md-4  my-3 row-sm">
                                                            <label for="{{ form.ap_paterno.id_for_label }}">
                                                                <h6>{{ form.ap_paterno.label }}</h6>
                                                            </label>
                                                            <div class="row d-flex justify-content-center">
                                                                <div class="">
                                                                    {{ form.ap_paterno }}
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-4 col-md-4  my-3 row-sm">
                                                            <label for="{{ form.ap_materno.id_for_label }}">
                                                                <h6>{{ form.ap_materno.label }}</h6>
                                                            </label>
                                                            <div class="row d-flex justify-content-center">
                                                                <div class="">
                                                                    {{ form.ap_materno }}
                                                                </div>
                                                            </div>
                                                        </div>

                                                        <div class="col-lg-4 col-md-4  my-3 row-sm">
                                                            <label for="{{ form.direccion.id_for_label }}">
                                                                <h6>{{ form.direccion.label }}</h6>
                                                            </label>
                                                            <div class="row d-flex justify-content-center">
                                                                <div class="">
                                                                    {{ form.direccion }}
                                                                </div>
                                                            </div>
                                                        </div>

                                                        <div class="col-lg-4 col-md-4  my-3 row-sm">
                                                            <label for="{{ form.documento.id_for_label }}">
                                                                <h6>{{ form.documento.label }}</h6>
                                                            </label>
                                                            <div class="row d-flex justify-content-center">
                                                                <div class="">
                                                                    {{ form.documento }}
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-4 col-md-4  my-3 row-sm">
                                                            <label for="{{ form.celular.id_for_label }}">
                                                                <h6>{{ form.celular.label }}</h6>
                                                            </label>
                                                            <div class="row d-flex justify-content-center">
                                                                <div class="">
                                                                    {{ form.celular }}
                                                                </div>
                                                            </div>
                                                        </div>

                                                    </div>
                                                
                                                
                                                    <div class="row d-flex justify-content-center mt-3">
                                                        <div class="col text-center">
                                                            <button type="submit" class="btn btn-primary" name="crear-cliente">Crear</button>
                                                        </div>
                                                    </div>
                                                </form>
                                                
        
                                                
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        

        <!-- termina accesos directos -->

      

        <a href="" style="text-decoration: none;">
          <footer class="footer">© Link-P</footer>
        </a>
  
      
  
  
    </div>


  
{% endblock content %}

<script src="{% static 'js/jquery-3.5.1.js' %}"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<script>
  
            const Toast = Swal.mixin({
              toast: true,
              position: 'top-end',
              showConfirmButton: false,
              timer: 3100,
              timerProgressBar: true,
              didOpen: (toast) => {
                toast.addEventListener('mouseenter', Swal.stopTimer)
                toast.addEventListener('mouseleave', Swal.resumeTimer)
              }
            })
          
            Toast.fire({
           
              imageHeight: 100,
              title: '{{mensaje}}, 
          
            })
       
</script>

templates/clientes/eliminar_cliente.html
{% extends "base.html" %}
{% load static %}
{% load tags_extras %}

{% block content %}

<div class="page-wrapper">
  <div class="container-fluid r-aside">

    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h3 class="text-themecolor">Borrar Proyecto
        </div>

        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'usuarios:home' %}">Inicio</a></li>
                <li class="breadcrumb-item"><a href="{% url 'proyectos:listar_proyectos' %}">Clientes</a>
                </li>
                <li class="breadcrumb-item">Borrar Cliente</li>
            </ol>
        </div>
    </div>
  </div>


  <div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body row">
                <div class="col-12 justify-content-center">
                  <div class="col bg-light border rounded p-4 ">

                    <div class="row d-flex justify-content-center">
                        <div class="col col-md-12 col-lg-12 text-center">

                            <h3> ¿Esta seguro de eliminar el Cliente:</h3>
                            <h1 class="text-primary"> {{cliente.nombres}}</h1>
                            <div>
                                <form method="post">
                                    {% csrf_token %}

                                    <button type='submit' class="btn btn-danger">Eliminar</button>
                                   
                                    <a href="{% url 'proyectos:listar_proyectos' %}" class="btn btn-secondary">Cancelar</a>

                                </form>
                            </div>

                        </div>
                    </div>
                  </div>
                </div>
            </div>
        </div>
    </div>
  </div>
</div>



{% endblock %}


  